// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlD5zBPGE7LcmkA6tUzw-iFxnwL4frYo',
    appId: '1:896546296461:web:c662ed4e0a8317656588c4',
    messagingSenderId: '896546296461',
    projectId: 'meeting-room-booking-app-3d637',
    authDomain: 'meeting-room-booking-app-3d637.firebaseapp.com',
    storageBucket: 'meeting-room-booking-app-3d637.firebasestorage.app',
    measurementId: 'G-3VQGPFX0CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6WMs3zDAbuKh_QaFXiNDlSFysgrCYUEY',
    appId: '1:896546296461:android:fba382851bed3e2d6588c4',
    messagingSenderId: '896546296461',
    projectId: 'meeting-room-booking-app-3d637',
    storageBucket: 'meeting-room-booking-app-3d637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK6Sc7XT70TT8otliWAEtCNNOkA86taQM',
    appId: '1:896546296461:ios:23003b4c57921a326588c4',
    messagingSenderId: '896546296461',
    projectId: 'meeting-room-booking-app-3d637',
    storageBucket: 'meeting-room-booking-app-3d637.firebasestorage.app',
    iosBundleId: 'com.example.meetingRoomBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK6Sc7XT70TT8otliWAEtCNNOkA86taQM',
    appId: '1:896546296461:ios:23003b4c57921a326588c4',
    messagingSenderId: '896546296461',
    projectId: 'meeting-room-booking-app-3d637',
    storageBucket: 'meeting-room-booking-app-3d637.firebasestorage.app',
    iosBundleId: 'com.example.meetingRoomBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPlD5zBPGE7LcmkA6tUzw-iFxnwL4frYo',
    appId: '1:896546296461:web:ee353afabd9e21c36588c4',
    messagingSenderId: '896546296461',
    projectId: 'meeting-room-booking-app-3d637',
    authDomain: 'meeting-room-booking-app-3d637.firebaseapp.com',
    storageBucket: 'meeting-room-booking-app-3d637.firebasestorage.app',
    measurementId: 'G-Y7GHVFN2ML',
  );
}
